services:
  oceanlaundry:
    image: oceanlaundry
    build:
      context: service
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    env_file:
      - ./service/.env
